In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "3"

2022-07-09 22:02:40.414000: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


In [6]:
z = tf.ones((32,2))
z

<tf.Tensor: shape=(32, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [13]:
r = tf.norm(z, axis=1)
a = 100.0
b = 100.0


<tf.Tensor: shape=(32,), dtype=float32, numpy=
array([-926.76184, -926.76184, -926.76184, -926.76184, -926.76184,
       -926.76184, -926.76184, -926.76184, -926.76184, -926.76184,
       -926.76184, -926.76184, -926.76184, -926.76184, -926.76184,
       -926.76184, -926.76184, -926.76184, -926.76184, -926.76184,
       -926.76184, -926.76184, -926.76184, -926.76184, -926.76184,
       -926.76184, -926.76184, -926.76184, -926.76184, -926.76184,
       -926.76184, -926.76184], dtype=float32)>